version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AutoCheckIn"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1e9m0wxfsm5ut"
s3_prefix = "AutoCheckIn"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

